project:
  type: website
  output-dir: docs
  
website:
  title: "Gwynnie's Epic Website!"
  navbar:
    right:
      - href: index.qmd
      - href: about.qmd
      - text: Computer Science
        menu: 
          - csproject.qmd
      - text: Data Science
        menu: 
          - tabs/miniproj1.qmd
          - tabs/miniproj2.qmd
          - tabs/salmon_tummys.Rmd
          - tabs/mp4.qmd
          - tabs/Wildfires.qmd
      - text: Statistics 
        menu: 
          - tabs/Stats2Project/finalProject.Rmd


        
format:
  html:
    standalone: TRUE
    theme: styles.scss 
    toc: true
    page-layout: full
    mainfont: Nanum Myeongjo

editor: visual
